package.path = "./?/init.lua;./?.lua;"..package.path
local net = require("lnet.tcp")
local multi, thread = require("multi"):init()
local server = net:newTCPServer(12345)
server:broadcast("Test")
print("Server has been broadcasted!")
server.OnDataRecieved(function(serv, data,cid)
    print("Response: ",data)
    server:send(cid,"Hello!")
end)
multi:mainloop()
